### ISSUE TITLE
在 Windows 下，正确填写配置文件后，程序异常退出

### ISSUE THREAD

**Issue by JueLuo99** [chr233/backup_by_mail#1]
Python 版本 3.8.3

```
C:\WINDOWS\system32>python e:\Code\backup_by_mail\run.py

[2020年07月12日]开始运行,按Ctrl+C终止
[15:28:28]程序出错name 'email_receiver' is not defined
Traceback (most recent call last):
  File "e:\Code\backup_by_mail\run.py", line 52, in <module>
    mail_log()
  File "e:\Code\backup_by_mail\run.py", line 18, in mail_log
    core.send_email(subject, message)
  File "e:\Code\backup_by_mail\core.py", line 77, in send_email
    mailobj['To'] = Header(f"{email_to}<{email_receiver}>", 'utf-8')
NameError: name 'email_receiver' is not defined
[2020年07月12日]运行结束
```

**Comment by JueLuo99** [comment]
定位到错误原因：`config.py.example` 文件中，第 9 行存在拼写错误
